# Generated by Django 4.0.3 on 2023-05-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='port_scan_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(default='', max_length=70)),
                ('domain', models.CharField(default='', max_length=200)),
                ('published', models.DateField(auto_now_add=True, verbose_name='DATE')),
                ('timeDateStart', models.DateTimeField(auto_now_add=True, verbose_name='DATE')),
                ('timeDateEnd', models.CharField(default='', max_length=70)),
                ('pending', models.IntegerField()),
            ],
        ),
    ]
