from django.urls import re_path
from django.urls import path
from tutorials import views 
from django.contrib import admin
urlpatterns = [ 
    
    path("",views.login,name="login"),
    re_path(r'^api/view/subdomain$', views.subdomainpage),
    # re_path(r'^register/ma',views.register, name='register'),
    re_path(r'^register$',views.registeruser, name='register_user'),
    re_path(r'^front$', views.front),
    re_path(r'^mainpage$', views.mainpage),
    re_path(r'^home$', views.userlogin,name='login_user'),
    re_path(r'^api/graphtable$', views.graphtable),
    re_path(r'^api/logout$', views.userlogout,name='logoutbtn'),
    # re_path(r'^api/showgraph/(?P<description>[a-z].+)', views.showgraph,name='showgraph'),
    re_path(r'^api/showgraph', views.showgraph,name='showgraph'),
    # re_path(r'^api/deletedomain/(?P<description>[a-z].+)', views.deletedomain,name='deletedomain'),
    re_path(r'^api/deletedomain',views.deletedomain,name="deletedomain"),
    re_path(r'^index$', views.index,name='index-file'),
    re_path(r'^api/tutorials$', views.tutorial_list,name='tutorial_list'),
    re_path(r'^api/load/graph/(?P<graphdomain>[a-z].+)', views.graph_json),
    # re_path(r'^api/load/graph$', views.graph_json),
    # re_path(r'^api/load/graph_list$', views.graph_list,name="graphlist"),
    # re_path(r'^api/load/graph_list$', views.graph_list,name="graphlist"),
    # re_path(r'^api/download/csv$', views.download_csv),
    re_path(r'^api/download/csv/([a-z].+)$', views.download_csv),
    re_path(r'^api/tutorials/(?P<pk>[0-9]+)$', views.tutorial_detail),
    re_path(r'^api/tutorials/published$', views.tutorial_list_published),
    re_path(r'^api/view/table$', views.table_view),

    re_path(r'^api/asset/subdomain.png$', views.asset_subdomain_png),
    re_path(r'^api/static/theme/webdatarocks-icons.ttf$', views.static_web_icons_ttf),
    re_path(r'^api/static/theme/webdatarocks-icons.woff$', views.static_web_icons_woff),
    re_path(r'^api/static/webdatarocks.min.css$', views.static_webdatatrocks_css),
    re_path(r'^api/static/webdatarocks.toolbar.min.js$', views.static_webdatatrocks_toolbar_js),
    re_path(r'^api/static/webdatarocks.js$', views.static_webdatatrocks_js),
re_path(r'^api/view/api/static/nmap.js$', views.static_nmap_js),
    re_path(r'^api/static/public/GiPerspectiveDiceSixFaces.svg$', views.static_public_GiPerspectiveDiceSixFaces_svg),
    re_path(r'^api/static/public/BiPlay.svg$', views.static_public_BiPlay_svg),
    re_path(r'^api/static/public/BiPause.svg$', views.static_public_BiPause_svg),
    re_path(r'^api/static/public/BiLoaderCircle.svg$', views.static_public_BiLoaderCircle_svg),
    re_path(r'^api/static/public/advanced-search.svg$', views.static_public_advanced_search_svg),
    re_path(r'^api/static/bundle.js$', views.static_bundle_js),
    # re_path(r'^api/api/showgraph/api/static/bundle.js$', views.static_bundle_js),
    re_path(r'^api/static/public/1.jpg$', views.static_public_1_jpg),
    re_path(r'^api/static/public/2.jpg$', views.static_public_2_jpg),
    re_path(r'^api/static/public/3.jpg$', views.static_public_3_jpg),
    re_path(r'^api/api/static/front.js$', views.static_front_js),
    re_path(r'^api/static/login.js$', views.static_login_js),
    re_path(r'^api/view/api/static/public/export-button-svgrepo-com.svg$', views.static_export_button_svgrepo_com_svg),
    re_path(r'^index/nmap$', views.nmap,name='nmap'),
    
    re_path(r'^api/static/public/abc.gif$', views.abc_gif),
    re_path(r'^api/static/public/bug.png$', views.bug_png),
    re_path(r'^api/static/public/c1.png$', views.c1_png),
    re_path(r'^api/static/public/c2.png$', views.c2_png),
    re_path(r'^api/static/public/hacker.png$', views.hacker_png),
    re_path(r'^api/static/public/team.png$', views.team_png),
      re_path(r'^api/static/public/testing.png$', views.testing_png),
    re_path(r'^api/static/public/white2.png$', views.white2_png),
    re_path(r'^api/static/public/world.png$', views.world_png),
    re_path(r'^api/nmapreport$', views.portinfo,name='nmapreport'),
    # re_path(r'^api/viewreport',views.deletedomain,name="deletedomain"),
]


