# Generated by Django 4.0.3 on 2022-08-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='pending',
            field=models.IntegerField(default=0),
        ),
    ]
