# Generated by Django 4.0.3 on 2022-08-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='pending',
            field=models.IntegerField(),
        ),
    ]
