# Generated by Django 4.0.3 on 2022-08-31 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
