# Generated by Django 4.0.3 on 2022-12-09 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attackeye', '0002_scan_timedatestart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='timeDateStart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
