# Generated by Django 4.0.3 on 2022-12-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackeye', '0004_alter_scan_timedatestart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='time',
        ),
        migrations.AddField(
            model_name='scan',
            name='timeDateEnd',
            field=models.DateTimeField(auto_now=True, verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='timeDateStart',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATE'),
        ),
    ]
