# Generated by Django 4.1.3 on 2022-12-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attackeye', '0005_remove_scan_time_scan_timedateend_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='description',
            new_name='domain',
        ),
    ]
