# Generated by Django 4.1.3 on 2022-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attackeye', '0006_rename_description_scan_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='timeDateEnd',
            field=models.CharField(default='', max_length=70),
        ),
    ]
