# Generated by Django 4.0.3 on 2022-12-13 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attackeye', '0007_alter_scan_timedateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='timeDateStart',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE'),
        ),
    ]
