"""
Django settings for attack_eye project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import sys
import dj_database_url
from decouple import Csv, config
import configparser
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# BASE_DIR = Path(__file__).resolve().parent.parent

SITE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__name__) + "../"))

sys.path.insert(0, os.path.join(BASE_DIR, "apps"))


config_parser = configparser.ConfigParser()
config_parser.read("/etc/attackeye/settings.ini")


# DEBUG setting
DEBUG = config_parser.getboolean(config("ENVIRONMENT"), "DEBUG")

# ALLOWED_HOSTS setting
ALLOWED_HOSTS = config_parser.get(config("ENVIRONMENT"), "ALLOWED_HOSTS").split(",")

# SECRET_KEY setting
SECRET_KEY = config_parser.get(config("ENVIRONMENT"), "SECRET_KEY")

# DATABASE_URL setting
DATABASES = {
    "default": dj_database_url.config(
        default=config_parser.get(config("ENVIRONMENT"), "DATABASE_URL"),
        conn_max_age=600,
    )
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "apps.core",
    "apps.amass",
]

MIDDLEWARE = [
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_session_timeout.middleware.SessionTimeoutMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = (
    "http://localhost:8081",
    "http://localhost:3000",
    "http://localhost:9000",
    "http://localhost:8080",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:9000",
    "http://127.0.0.1:8080",
)

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

CELERY_BROKER_URL = "amqp://localhost"
CELERY_IMPORTS = ("apps.core.tasks",)

WSGI_APPLICATION = "config.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/


# LANGUAGE_CODE setting
LANGUAGE_CODE = config_parser.get(
    config("ENVIRONMENT"), "LANGUAGE_CODE", fallback="en-us"
)

# TIME_ZONE setting
TIME_ZONE = config_parser.get(
    config("ENVIRONMENT"), "TIME_ZONE", fallback="Asia/Karachi"
)

# Internationalization
LANGUAGES = [
    ("en-us", _("English")),
    ("es", _("Spanish")),
    # Add other languages that you want to support
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


LOGIN_URL = "/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SESSION_EXPIRE_SECONDS = 43200
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True

# ==============================================================================
# MEDIA FILES SETTINGS
# ==============================================================================

# MEDIA_URL = "/media/"

# MEDIA_ROOT = BASE_DIR.parent.parent / "media"


# ==============================================================================
# THIRD-PARTY SETTINGS
# ==============================================================================


# ==============================================================================
# FIRST-PARTY SETTINGS
# ==============================================================================

SIMPLE_ENVIRONMENT = config("SIMPLE_ENVIRONMENT", default="local")
